services:
  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Upako@12345
      MYSQL_DATABASE: upako
      MYSQL_USER: root
      MYSQL_PASSWORD: Upako@12345
    ports:
      - "4000:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    command: ./wait-for-it.sh python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db_data:
