# Generated by Django 5.2.1 on 2025-06-21 22:12

import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FellowshipMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('original_location', django_countries.fields.CountryField(max_length=2)),
                ('current_location_region', models.CharField(choices=[('Shinyanga', 'Shinyanga'), ('Mara', 'Mara'), ('Dar-es-salaam', 'Dar-es-salaam'), ('Kilimanjaro', 'Kilimanjaro'), ('Kagera', 'Kagera'), ('Tanga', 'Tanga'), ('Mwanza', 'Mwanza'), ('Tabora', 'Tabora'), ('Kigoma', 'Kigoma'), ('Pwani', 'Pwani'), ('Ruvuma', 'Ruvuma'), ('Mtwara', 'Mtwara'), ('Morogoro', 'Morogoro'), ('Rukwa', 'Rukwa'), ('Katavi', 'Katavi'), ('Simiyu', 'Simiyu'), ('Geita', 'Geita'), ('Arusha', 'Arusha'), ('Iringa', 'Iringa'), ('Mbeya', 'Mbeya'), ('Njombe', 'Njombe'), ('Manyara', 'Manyara'), ('Lindi', 'Lindi'), ('Singida', 'Singida'), ('Songwe', 'Songwe'), ('Dodoma', 'Dodoma')], max_length=100)),
                ('current_location_district', models.CharField(max_length=100)),
                ('current_location_ward', models.CharField(max_length=100)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married')], max_length=10)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_arrival', models.DateField()),
                ('date_of_departure', models.DateField(blank=True, null=True)),
                ('occupation', models.CharField(max_length=100)),
                ('passport_number', models.CharField(blank=True, max_length=50)),
                ('ticket', models.FileField(blank=True, upload_to='tickets/')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FellowshipMember',
                'ordering': ['-created_at'],
            },
        ),
    ]
