# Generated by Django 5.2.1 on 2025-06-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('attachments', models.FileField(blank=True, null=True, upload_to='complaint_attachments/')),
                ('status', models.CharField(choices=[('Opened', 'Opened'), ('Forwarded', 'Forwarded'), ('Closed', 'Closed')], default='Opened', max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Opened', 'Opened'), ('Forwarded', 'Forwarded'), ('Closed', 'Closed')], default='Opened', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('attachments', models.FileField(blank=True, null=True, upload_to='remark_attachments/')),
                ('status', models.CharField(choices=[('Opened', 'Opened'), ('Forwarded', 'Forwarded'), ('Closed', 'Closed')], default='Opened', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
