# Generated by Django 5.2.1 on 2025-06-21 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complainant',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='targeted_personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_against', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='targeted_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_department', to='complaints.department'),
        ),
        migrations.AddField(
            model_name='departmenthistory',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.complaint'),
        ),
        migrations.AddField(
            model_name='departmenthistory',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.department'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='department_history',
            field=models.ManyToManyField(blank=True, related_name='history', through='complaints.DepartmentHistory', to='complaints.department'),
        ),
        migrations.AddField(
            model_name='remark',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='complaints.complaint'),
        ),
        migrations.AddField(
            model_name='remark',
            name='remark_targeted_department',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='complaints.department'),
        ),
        migrations.AddField(
            model_name='remark',
            name='remark_targeted_personnel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remark_target', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remark',
            name='respondent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
