# Generated by Django 5.2.1 on 2025-06-21 22:12

import django.utils.timezone
import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('dob', models.DateField()),
                ('twins_status', models.CharField(choices=[('single', 'Single'), ('double', 'Twins'), ('triple', 'Triplets')], max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('health_status', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(choices=[('Shinyanga', 'Shinyanga'), ('Mara', 'Mara'), ('Dar-es-salaam', 'Dar-es-salaam'), ('Kilimanjaro', 'Kilimanjaro'), ('Kagera', 'Kagera'), ('Tanga', 'Tanga'), ('Mwanza', 'Mwanza'), ('Tabora', 'Tabora'), ('Kigoma', 'Kigoma'), ('Pwani', 'Pwani'), ('Ruvuma', 'Ruvuma'), ('Mtwara', 'Mtwara'), ('Morogoro', 'Morogoro'), ('Rukwa', 'Rukwa'), ('Katavi', 'Katavi'), ('Simiyu', 'Simiyu'), ('Geita', 'Geita'), ('Arusha', 'Arusha'), ('Iringa', 'Iringa'), ('Mbeya', 'Mbeya'), ('Njombe', 'Njombe'), ('Manyara', 'Manyara'), ('Lindi', 'Lindi'), ('Singida', 'Singida'), ('Songwe', 'Songwe'), ('Dodoma', 'Dodoma')], max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Baby',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('weeks_of_pregnancy', models.PositiveIntegerField()),
                ('expected_delivery_date', models.DateField()),
                ('is_active_pregnancy', models.BooleanField(default=True)),
                ('delivery_place_region', models.CharField(choices=[('Shinyanga', 'Shinyanga'), ('Mara', 'Mara'), ('Dar-es-salaam', 'Dar-es-salaam'), ('Kilimanjaro', 'Kilimanjaro'), ('Kagera', 'Kagera'), ('Tanga', 'Tanga'), ('Mwanza', 'Mwanza'), ('Tabora', 'Tabora'), ('Kigoma', 'Kigoma'), ('Pwani', 'Pwani'), ('Ruvuma', 'Ruvuma'), ('Mtwara', 'Mtwara'), ('Morogoro', 'Morogoro'), ('Rukwa', 'Rukwa'), ('Katavi', 'Katavi'), ('Simiyu', 'Simiyu'), ('Geita', 'Geita'), ('Arusha', 'Arusha'), ('Iringa', 'Iringa'), ('Mbeya', 'Mbeya'), ('Njombe', 'Njombe'), ('Manyara', 'Manyara'), ('Lindi', 'Lindi'), ('Singida', 'Singida'), ('Songwe', 'Songwe'), ('Dodoma', 'Dodoma')], max_length=100)),
                ('delivery_place_district', models.CharField(max_length=100)),
                ('nationality', django_countries.fields.CountryField(default='TZ', max_length=2)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('delivery_method', models.CharField(choices=[('normal', 'Normal Delivery'), ('cesarean', 'Cesarean Section'), ('induced', 'Induced')], max_length=50)),
                ('delivery_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(default=django.utils.timezone.now)),
                ('vitals', models.TextField()),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'VisitRecord',
                'ordering': ['-created_at'],
            },
        ),
    ]
