# Generated by Django 5.2.1 on 2025-06-21 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ariseclinic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='attended_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__name__in': ['Doctor', 'Nurse']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='baby',
            name='mother',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='babies', to='ariseclinic.patient'),
        ),
        migrations.AddField(
            model_name='visitrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ariseclinic.patient'),
        ),
        migrations.AddField(
            model_name='visitrecord',
            name='seen_by',
            field=models.ForeignKey(limit_choices_to={'role__name__in': ['Doctor', 'Nurse']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
